version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01
        working_directory: ~/repo
        steps:
          - checkout
          - run:
              name: Install Docker & Docker Compose
              command: |
                  sudo apt update
                  sudo apt-get remove docker docker-engine docker.io containerd runc
                  sudo apt install docker-ce docker-ce-cli containerd.io
                  curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                  chmod +x ~/docker-compose
                  sudo mv ~/docker-compose /usr/local/bin/docker-compose
                  docker pull onopon/lolipop_web_server_for_python3:latest

                  #          - run:
                  #              name: docker-compose up
                  #              command: |
                  #                  set -x
                  #                  docker-compose up --build -d
                  #          - run:
                  #              name: docker-compose stop
                  #              command: |
                  #                  set -x
                  #                  docker-compose stop
          - run:
              name: docker-compose up
              command: |
                  set -x
                  docker-compose up -d
          - run:
              name: Run flake8, mypy, pytest
              command: |
                  ./test/run
          - run:
              name: docker-compose down
              command: docker-compose down
