version: 2.1

jobs:
  flake8-mypy-test:
    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Run flake8
          command: |
            poetry run flake8
      - run:
          name: Run mypy
          command: |
            poetry run mypy ./
      - run:
          name: Run Pytest, report
          command: |
            poetry run pytest tests/
workflows:
  main:
    jobs:
      - flake8-mypy-test
