version: 2.1

jobs:
  flake8-mypy-test:
    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: |
            pip install --user --upgrade pip
            pip install --user -r requirements_dev.txt
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

              #      - run:
              #          name: Run flake8
              #          command: |
              #            flake8
              #      - run:
              #          name: Run mypy
              #          command: |
              #            mypy ./
      - run:
          name: Run Pytest, report
          command: |
            pytest tests/
workflows:
  main:
    jobs:
      - flake8-mypy-test
