"""empty message

Revision ID: 52765071a484
Revises: 67d011797783
Create Date: 2021-03-27 21:49:22.668917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52765071a484'
down_revision = '67d011797783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_points', sa.Column('available_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus_points', 'available_count')
    # ### end Alembic commands ###
