"""empty message

Revision ID: 9d2e4bec2f63
Revises: 085db56c10ae
Create Date: 2021-03-15 20:33:29.433390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2e4bec2f63'
down_revision = '085db56c10ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_user_id'), 'roles', ['user_id'], unique=False)
    op.add_column('leagues', sa.Column('end_at', sa.Time(), nullable=False))
    op.add_column('leagues', sa.Column('is_decided', sa.Boolean(), nullable=False))
    op.add_column('leagues', sa.Column('join_end_at', sa.DateTime(), nullable=False))
    op.add_column('leagues', sa.Column('place_id', sa.Integer(), nullable=False))
    op.add_column('leagues', sa.Column('start_at', sa.Time(), nullable=False))
    op.create_index(op.f('ix_leagues_place_id'), 'leagues', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leagues_place_id'), table_name='leagues')
    op.drop_column('leagues', 'start_at')
    op.drop_column('leagues', 'place_id')
    op.drop_column('leagues', 'join_end_at')
    op.drop_column('leagues', 'is_decided')
    op.drop_column('leagues', 'end_at')
    op.drop_index(op.f('ix_roles_user_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('places')
    # ### end Alembic commands ###
