"""empty message

Revision ID: bd996cd60504
Revises: 
Create Date: 2021-03-21 02:50:19.691477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd996cd60504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_log_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_log_id', sa.Integer(), nullable=False),
    sa.Column('score_1', sa.Integer(), nullable=False),
    sa.Column('score_2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_log_details_league_log_id'), 'league_log_details', ['league_log_id'], unique=False)
    op.create_table('league_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_user_id_1_and_2', 'league_logs', ['user_id_1', 'user_id_2'], unique=False)
    op.create_index(op.f('ix_league_logs_league_id'), 'league_logs', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_logs_user_id_1'), 'league_logs', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_league_logs_user_id_2'), 'league_logs', ['user_id_2'], unique=False)
    op.create_table('league_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_members_league_id'), 'league_members', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_members_user_id'), 'league_members', ['user_id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.Time(), nullable=False),
    sa.Column('end_at', sa.Time(), nullable=False),
    sa.Column('join_end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_date'), 'leagues', ['date'], unique=False)
    op.create_index(op.f('ix_leagues_game_count'), 'leagues', ['game_count'], unique=False)
    op.create_index(op.f('ix_leagues_place_id'), 'leagues', ['place_id'], unique=False)
    op.create_index(op.f('ix_leagues_status'), 'leagues', ['status'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_user_id'), 'roles', ['user_id'], unique=False)
    op.create_table('user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_league_id'), 'user_points', ['league_id'], unique=False)
    op.create_index(op.f('ix_user_points_user_id'), 'user_points', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login_name'), 'users', ['login_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_points_user_id'), table_name='user_points')
    op.drop_index(op.f('ix_user_points_league_id'), table_name='user_points')
    op.drop_table('user_points')
    op.drop_index(op.f('ix_roles_user_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('places')
    op.drop_index(op.f('ix_leagues_status'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_place_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_game_count'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_date'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_league_members_user_id'), table_name='league_members')
    op.drop_index(op.f('ix_league_members_league_id'), table_name='league_members')
    op.drop_table('league_members')
    op.drop_index(op.f('ix_league_logs_user_id_2'), table_name='league_logs')
    op.drop_index(op.f('ix_league_logs_user_id_1'), table_name='league_logs')
    op.drop_index(op.f('ix_league_logs_league_id'), table_name='league_logs')
    op.drop_index('index_user_id_1_and_2', table_name='league_logs')
    op.drop_table('league_logs')
    op.drop_index(op.f('ix_league_log_details_league_log_id'), table_name='league_log_details')
    op.drop_table('league_log_details')
    # ### end Alembic commands ###
