name: Test

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      APP_IMAGE_TAG: onopon/lolipop_web_server_for_python3
      APP_IMAGE_CACHE_TAG: 20210617
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}

    - name: cache-images
      id: cache-images
      uses: actions/cache@v2
      with:
        path: /tmp/images
        key: ${{ env.APP_IMAGE_TAG }}-${{ env.APP_IMAGE_CACHE_TAG }}
        restore-keys: |
          ${{ env.APP_IMAGE_TAG }}-${{ env.APP_IMAGE_CACHE_TAG }}

    - name: load image
      id: load-image
      if: steps.cache-images.outputs.cache-hit == 'true'
      run: |
        image_id=`docker image load -i /tmp/images/lolipop_web_server_for_python3.tar | cut -d ':' -f 3 | cut -c 1-6`
        docker tag $image_id onopon/lolipop_web_server_for_python3:latest

    - name: pull image
      if: steps.load-image.conclusion == 'skipped'
      run: docker pull onopon/lolipop_web_server_for_python3:latest

    - name: save image
      if: steps.load-image.conclusion == 'skipped'
      run: |
        mkdir -p /tmp/images
        web_image_id=`docker images --format "{{.ID}} {{.Repository}}" | grep lolipop_web_server_for_python3 | cut -d ' ' -f1`
        docker save -o /tmp/images/lolipop_web_server_for_python3.tar ${{ APP_IMAGE_TAG }}:latest

    - name: docker compose up
      run: |
        docker-compose up -d

    - name: Waiting start app
      shell: bash
      run: |
        .github/waiting_start_app.sh

    - name: Run flake8
      shell: bash
      run:  |
        echo "SKIP"
#        docker-compose exec -T test-app flake8 ./

    - name: Run mypy
      shell: bash
      run:  |
        echo "SKIP"
#        docker-compose exec -T test-app --ignore-missing-imports ./

    - name: Run Pytest
      shell: bash
      run:  |
        docker-compose exec -T test-app pytest tests/
